language: c

# As much as I hate to force a distro,
# There was an issue with pkg-config and cunit in 2.1.2
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=782366
# Which is fixed in 2.1.3
# However, the 2.1.3 version is only available in xenial+
# https://launchpad.net/ubuntu/+source/cunit
dist: xenial

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get install -y libcunit1 libcunit1-dev
  - mkdir build
  - cd build
  - cmake ..

script: make && make test

